async function getLaunchDemandRequests(){
  const local=SulitLaunch.getRequests().filter(r=>r.status!=='fulfilled');
  const cloud=await SulitLaunch.loadCloudRequests();
  if(!cloud.length)return local;
  const groups=new Map();
  cloud.forEach(row=>{const key=row.normalized_query;let g=groups.get(key);if(!g){g={id:`cloud:${key}`,key,query:row.display_query,status:'pending',searchCount:0,userIds:[],createdAt:row.created_at,updatedAt:row.updated_at,cloud:true};groups.set(key,g)}g.searchCount+=1;if(!g.userIds.includes(row.user_id))g.userIds.push(row.user_id);if(new Date(row.created_at)<new Date(g.createdAt))g.createdAt=row.created_at});
  local.forEach(row=>{if(!groups.has(row.key))groups.set(row.key,row)});
  return [...groups.values()];
}
async function renderLaunchAdmin(){
  const prices=getPrices(); const tasks=prices.map(p=>{const f=SulitLaunch.freshness(p);return {...p,freshness:f,product:productById(p.productId),store:storeById(p.storeId)}}).sort((a,b)=>(b.freshness.days??999)-(a.freshness.days??999));
  const due=tasks.filter(t=>t.freshness.days===null||t.freshness.days>4); const stale=tasks.filter(t=>t.freshness.days===null||t.freshness.days>10);
  const stats=document.getElementById('launchTaskStats'); if(stats)stats.innerHTML=`<div class="admin-launch-card"><div class="muted">Due now</div><div class="value">${due.length}</div></div><div class="admin-launch-card"><div class="muted">Older than 10 days</div><div class="value">${stale.length}</div></div><div class="admin-launch-card"><div class="muted">Fresh prices</div><div class="value">${tasks.length-due.length}</div></div>`;
  const count=document.getElementById('launchTaskCount');if(count)count.textContent=`${due.length} due`;
  const rows=document.getElementById('launchTaskRows');if(rows)rows.innerHTML=due.length?due.slice(0,100).map(t=>`<div class="admin-request-row"><div class="request-main"><strong>${productIcon(t.product)} ${t.product?.name||'Unknown'}</strong><div class="muted">${t.product?.brand||''} · ${t.product?.unit||''}</div></div><div>${t.store?.name||'Store'}</div><div><strong>${money(t.price)}</strong></div><div class="${t.freshness.state==='fresh'?'task-fresh':'task-stale'}">${t.freshness.label}</div><div class="request-actions"><button class="secondary compact-button" onclick="openAdminTab('prices');editAdminPrice(${t.productId},${t.storeId})">Update price</button></div></div>`).join(''):'<div class="empty muted">All prices are fresh.</div>';
  const requests=(await getLaunchDemandRequests()).sort((a,b)=>(b.userIds?.length||0)-(a.userIds?.length||0)||Number(b.searchCount||0)-Number(a.searchCount||0));
  window.__launchDemandRequests=requests;
  const dStats=document.getElementById('launchDemandStats');if(dStats)dStats.innerHTML=`<div class="admin-launch-card"><div class="muted">Pending requests</div><div class="value">${requests.length}</div></div><div class="admin-launch-card"><div class="muted">Unique shoppers</div><div class="value">${new Set(requests.flatMap(r=>r.userIds||[])).size}</div></div><div class="admin-launch-card"><div class="muted">Total searches</div><div class="value">${requests.reduce((n,r)=>n+Number(r.searchCount||0),0)}</div></div>`;
  const dCount=document.getElementById('launchDemandCount');if(dCount)dCount.textContent=`${requests.length} pending`;
  const dRows=document.getElementById('launchDemandRows');if(dRows)dRows.innerHTML=requests.length?requests.map((r,i)=>`<div class="admin-request-row"><div class="request-main"><strong>${safeText(r.query)}</strong><div class="muted">First requested ${new Date(r.createdAt).toLocaleDateString()}</div></div><div><span class="priority-pill">${(r.userIds?.length||0)>=5?'High':'Standard'}</span></div><div>${r.searchCount||0} searches</div><div>${r.userIds?.length||0} shoppers</div><div class="request-actions"><button class="secondary compact-button" onclick="startRequestedProduct(${i})">Add product</button></div></div>`).join(''):'<div class="empty muted">No pending product requests.</div>';
}
function startRequestedProduct(index){const r=window.__launchDemandRequests?.[index];if(!r)return;openAdminTab('products');const input=document.getElementById('adminProductName');if(input){input.value=r.query;input.focus();input.dataset.requestId=r.id;input.dataset.requestKey=r.key;input.dataset.requestCloud=String(Boolean(r.cloud))}const title=document.getElementById('productFormTitle');if(title)title.textContent='Add requested product';}
(function(){const original=window.saveAdminProduct;if(typeof original==='function'){window.saveAdminProduct=async function(){const input=document.getElementById('adminProductName');const requestId=input?.dataset?.requestId;const requestKey=input?.dataset?.requestKey;const cloud=input?.dataset?.requestCloud==='true';const name=input?.value;const productId=Number(document.getElementById('productEditId')?.value||0)||null;const result=await original.apply(this,arguments);if(requestId&&name){if(cloud&&requestKey)await SulitLaunch.fulfillCloudQuery(requestKey,productId,name);else SulitLaunch.fulfillRequest(requestId,name);delete input.dataset.requestId;delete input.dataset.requestKey;delete input.dataset.requestCloud;setTimeout(renderLaunchAdmin,100)}return result}}})();
document.addEventListener('DOMContentLoaded',renderLaunchAdmin);
